name: run script with secret
on:
  workflow_dispatch:
jobs:
  run-script-with-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: node ./test.js ${{ secrets.SuperSecret }}
